import { Header } from "@/components/Header"
import { Footer } from "@/components/Footer"
import { Breadcrumbs } from "@/components/Breadcrumbs"
import { Prose } from "@/components/Prose"
import { buildMetadata } from "@/lib/site"
import { buildBreadcrumbJsonLd } from "@/lib/json-ld"
import { getVendors, getVendorBySlug } from "@/content/data"
import { notFound } from "next/navigation"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  Clock01Icon,
  AnalyticsUpIcon,
  Link01Icon,
  HelpSquareIcon,
  File02Icon,
  Target01Icon,
  ShoppingCart01Icon,
} from "@hugeicons/core-free-icons"
import Link from "next/link"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { MegaGlossary } from "@/components/MegaGlossary"

export async function generateStaticParams() {
  return getVendors().map((vendor) => ({
    slug: vendor.slug,
  }))
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const resolvedParams = await params
  const vendor = getVendorBySlug(resolvedParams.slug)
  if (!vendor) return {}

  return buildMetadata({
    title: `${vendor.name} Tracking Data`,
    description: `Independent verification of the claims and performance metrics for ${vendor.name} against the S&P 500 benchmark index over time.`,
    path: `/tools/${vendor.slug}/`,
  })
}

export default async function VendorPage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const resolvedParams = await params
  const vendor = getVendorBySlug(resolvedParams.slug)

  if (!vendor) {
    notFound()
  }

  const jsonLd = buildBreadcrumbJsonLd([
    { name: "Tools", item: "/tools/" },
    { name: vendor.name, item: `/tools/${vendor.slug}/` },
  ])

  return (
    <div className="flex min-h-screen flex-col">
      <Header />

      <main className="flex-1 bg-background py-16 md:py-24">
        <div className="container mx-auto max-w-4xl px-4 md:px-8">
          <Breadcrumbs
            items={[
              { name: "Tools", href: "/tools/" },
              { name: vendor.name, href: `/tools/${vendor.slug}/` },
            ]}
          />

          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
          />

          <article>
            <div className="mb-12">
              <span className="mb-4 block flex items-center gap-2 font-mono text-xs tracking-widest text-muted-foreground uppercase">
                <HugeiconsIcon icon={AnalyticsUpIcon} className="h-4 w-4" />{" "}
                {vendor.category}
              </span>
              <h1 className="text-display mb-6">{vendor.name} Verification</h1>
              <p className="text-lead mb-8 max-w-3xl">
                {vendor.description} This page documents our ongoing,
                independent evaluation of the algorithm's performance. By
                applying our strict holding-period constraints and comparing
                output directly against the SPY ETF, we isolate the true alpha
                generated by the platform.
              </p>
              <div className="inline-flex items-center gap-2 rounded-md bg-muted px-3 py-1.5 font-mono text-sm text-muted-foreground">
                <HugeiconsIcon icon={Clock01Icon} className="h-4 w-4" /> STATUS:{" "}
                {vendor.status.toUpperCase()}
              </div>
            </div>

            {/* Matrix of Claims */}
            <section className="mb-16">
              <div className="mb-6 flex items-center gap-2">
                <HugeiconsIcon
                  icon={File02Icon}
                  className="h-5 w-5 text-muted-foreground"
                />
                <h2 className="text-h3 m-0">Marketing Claims Matrix</h2>
              </div>
              <div className="mb-8 w-full overflow-x-auto rounded-lg border bg-card">
                <table className="w-full min-w-[600px] border-collapse text-left">
                  <thead>
                    <tr className="border-b bg-muted/50">
                      <th className="px-6 py-4 font-heading text-sm font-semibold">
                        Metric
                      </th>
                      <th className="px-6 py-4 font-heading text-sm font-semibold">
                        Claimed Value
                      </th>
                      <th className="px-6 py-4 font-heading text-sm font-semibold">
                        Verification Date
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b border-border/50 transition-colors hover:bg-muted/30">
                      <td className="flex items-center gap-2 px-6 py-4 text-sm font-medium tracking-wider text-muted-foreground uppercase">
                        <HugeiconsIcon
                          icon={ShoppingCart01Icon}
                          className="h-4 w-4"
                        />{" "}
                        Subscription Cost
                      </td>
                      <td className="px-6 py-4 font-mono font-medium">
                        {vendor.cost.value}
                      </td>
                      <td className="px-6 py-4 font-mono text-sm text-muted-foreground">
                        {vendor.cost.verificationDate}
                      </td>
                    </tr>
                    <tr className="border-b border-border/50 transition-colors hover:bg-muted/30">
                      <td className="flex items-center gap-2 px-6 py-4 text-sm font-medium tracking-wider text-muted-foreground uppercase">
                        <HugeiconsIcon
                          icon={Target01Icon}
                          className="h-4 w-4"
                        />{" "}
                        Win Rate
                      </td>
                      <td className="px-6 py-4 font-mono font-medium">
                        {vendor.claimedWinRate.value}
                      </td>
                      <td className="px-6 py-4 font-mono text-sm text-muted-foreground">
                        {vendor.claimedWinRate.verificationDate}
                      </td>
                    </tr>
                    <tr className="transition-colors hover:bg-muted/30">
                      <td className="flex items-center gap-2 px-6 py-4 text-sm font-medium tracking-wider text-muted-foreground uppercase">
                        <HugeiconsIcon
                          icon={AnalyticsUpIcon}
                          className="h-4 w-4"
                        />{" "}
                        Alpha vs SPY
                      </td>
                      <td className="px-6 py-4 font-mono font-medium">
                        {vendor.claimedAlpha.value}
                      </td>
                      <td className="px-6 py-4 font-mono text-sm text-muted-foreground">
                        {vendor.claimedAlpha.verificationDate}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <Prose className="max-w-none">
                <p>
                  The claims documented above are extracted directly from the
                  vendor's marketing materials on the specified verification
                  date. Vendors frequently alter these numbers when confronted
                  with adverse market conditions. By logging the exact claim and
                  linking it to a timestamp, we establish a firm baseline
                  against which the algorithm must prove itself.
                </p>
                <p>
                  If the vendor claims an exceptionally high win rate, our
                  tracking apparatus will ruthlessly expose whether that metric
                  relies on microscopic price movements or ignores standard
                  retail trading friction. If the vendor claims high absolute
                  returns, we verify whether those returns actually generated
                  alpha when mapped against the equivalent SPY holding period.
                </p>
              </Prose>
            </section>

            <section className="mb-16 border-t pt-16">
              <h2 className="text-h2 mb-6">Data Collection Status</h2>
              <Prose className="max-w-none">
                <p>
                  This tool is currently in the <strong>{vendor.status}</strong>{" "}
                  phase. We are actively monitoring and logging all published
                  trade recommendations. To ensure statistical significance, we
                  require a minimum 90-day baseline holding period before
                  generating the first comparative alpha report against the S&P
                  500 benchmark.
                </p>
                <p>
                  Once the initial baseline period concludes, a live performance
                  chart will be rendered here, plotting the aggregate return of
                  the captured signals directly against the SPY ETF over the
                  identical timeframe. This ensures retail investors have access
                  to data unaffected by retroactive adjustments.
                </p>

                <h3>Methodology Application</h3>
                <p>
                  As part of our commitment to independent tracking, every
                  signal generated by {vendor.name} is treated as an actionable
                  mandate. We do not apply discretionary filtering to the
                  signals. If the platform recommends a trade, it is logged at
                  the next available opening market price.
                </p>
                <p>
                  This zero-discretion approach prevents the unintentional
                  introduction of human bias into the algorithmic evaluation.
                  The core premise of paying for an AI stock picker is the
                  removal of emotional trading; our tracking mirrors this
                  expectation precisely.
                </p>

                <h3>Holding Period Constraints</h3>
                <p>
                  Unless {vendor.name} explicitly provides a target holding
                  duration for a specific trade (e.g., a "two-week swing"), we
                  enforce a default 90-day holding window. This aligns with
                  standard quarterly reporting cycles and prevents
                  high-frequency noise from distorting long-term predictive
                  accuracy.
                </p>
                <p>
                  If a position reaches a vendor-specified stop-loss or
                  take-profit threshold before the holding period expires, the
                  position is closed in our tracking matrix, and the final
                  return is recorded against the SPY equivalent return up to
                  that exact date. This prevents vendors from claiming success
                  on trades that technically hit a target but would have stopped
                  out a real investor along the way.
                </p>
              </Prose>
            </section>

            <section className="mb-16 border-t pt-16">
              <div className="mb-8 flex items-center gap-2">
                <HugeiconsIcon
                  icon={HelpSquareIcon}
                  className="h-6 w-6 text-muted-foreground"
                />
                <h2 className="text-h2 m-0">Evaluation FAQ</h2>
              </div>
              <Accordion type="single" collapsible className="mb-12 w-full">
                <AccordionItem value="item-1">
                  <AccordionTrigger className="font-heading text-lg">
                    Does this tracking account for commission fees?
                  </AccordionTrigger>
                  <AccordionContent className="text-body text-muted-foreground">
                    Our current baseline metrics do not calculate broker
                    commissions or slippage. We track the pure opening price
                    differential to evaluate the core algorithmic edge. Retail
                    investors should assume their actual net returns will be
                    slightly lower due to execution costs, particularly if{" "}
                    {vendor.name} suggests high-frequency portfolio rotation.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-2">
                  <AccordionTrigger className="font-heading text-lg">
                    When will the baselining phase conclude?
                  </AccordionTrigger>
                  <AccordionContent className="text-body text-muted-foreground">
                    Baselining requires a minimum of 90 days of continuous data
                    capture from our initiation date. This ensures we have a
                    statistically meaningful sample size of market environments
                    (up days, down days, volatility spikes) to fairly compare{" "}
                    {vendor.name}'s performance against the SPY benchmark.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-3">
                  <AccordionTrigger className="font-heading text-lg">
                    Can the vendor alter past recommendations?
                  </AccordionTrigger>
                  <AccordionContent className="text-body text-muted-foreground">
                    No. Our system captures and timestamps the trade signal the
                    moment it is published to the vendor's platform or sent via
                    alert. Even if the vendor subsequently deletes or modifies a
                    losing trade from their own dashboard to improve their
                    marketed win rate, our immutable ledger retains the original
                    signal for the alpha calculation.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-4">
                  <AccordionTrigger className="font-heading text-lg">
                    Why use the S&P 500 (SPY) as the benchmark?
                  </AccordionTrigger>
                  <AccordionContent className="text-body text-muted-foreground">
                    The SPY ETF represents the opportunity cost of capital for
                    the average retail investor. It requires zero research time
                    and negligible fees. If an expensive AI subscription cannot
                    consistently outperform this zero-effort baseline over a
                    sustained period, the algorithmic edge is negative,
                    regardless of its absolute positive returns during a bull
                    market.
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-5">
                  <AccordionTrigger className="font-heading text-lg">
                    How is survivorship bias mitigated here?
                  </AccordionTrigger>
                  <AccordionContent className="text-body text-muted-foreground">
                    By logging the entry signal immediately and holding it
                    virtually to its conclusion, we strip the vendor of the
                    ability to selectively highlight winners while ignoring
                    losers. The final alpha calculation includes the totality of
                    the generated signals across the tracked horizon, presenting
                    a mathematically accurate representation of the tool's
                    performance.
                  </AccordionContent>
                </AccordionItem>
              </Accordion>

              <div className="mb-8 flex items-center gap-2">
                <HugeiconsIcon
                  icon={HelpSquareIcon}
                  className="h-6 w-6 text-muted-foreground"
                />
                <h2 className="text-h2 m-0">Metric Context Glossary</h2>
              </div>
              <MegaGlossary count={25} />
            </section>

            <section className="border-t pt-16">
              <h2 className="text-h3 mb-6">Compare Other Tools</h2>
              <div className="flex flex-col gap-3">
                {getVendors()
                  .filter((v) => v.slug !== vendor.slug)
                  .slice(0, 2)
                  .map((sibling) => (
                    <div key={sibling.slug}>
                      <Link
                        href={`/tools/${sibling.slug}/`}
                        className="flex w-fit items-center gap-2 rounded border bg-muted/30 px-4 py-3 text-accent transition-colors hover:bg-muted/50 hover:underline"
                      >
                        <HugeiconsIcon icon={Link01Icon} className="h-4 w-4" />{" "}
                        View {sibling.name} Verification
                      </Link>
                    </div>
                  ))}
                <div>
                  <Link
                    href="/tools/"
                    className="mt-6 flex w-fit items-center gap-2 font-medium text-muted-foreground transition-colors hover:text-foreground"
                  >
                    &larr; Return to Tools Directory
                  </Link>
                </div>
              </div>
            </section>
          </article>
        </div>
      </main>

      <Footer />
    </div>
  )
}
